# **Numpy** (numerical python)
- It stand for numerical python.
- it is used for numerical computation
- it provide support for large multi-dimensional arrays and matrices along with a collection of highe-level mathematical function to operates on these arrays.

**features of NumPy**
1. **supports operation on N-dimensional arrays** - N-dimensional array also known as (n-D array) is a core data structure used in numpy for efficient storage and computation.
2. **numpy allows broadcasting** i.e. arithematic operation on arrays of different shapes.
3. **numpy also allow vectorization** i.e. eliminating needs for loops during operations on array.
4. Numpy provides built-in support for linear algebra, statistics, trigonometry calculation
5. numpy can be integrated with other python libraries like pandas, matplotlib, seaborn, scikit learn etc.

**Data structure in numpy**

- numpy primerily words with single core data structure. n-D array
1. **n-dimensional array**
- This can be of any (N) dimensions
- N-D array can represent vectors (1D array) matrices (2D array) or tensors (3-D array)
- N-D array are homogeneous which means all elements value in N-D array must be of same datatype
- this array are of fixed size , once created we cannot change size of array

2. **Structured array**
- These arrays are **heterogeneous** arrays i.e. used to handle , store data of different datatypes similar to SQL, dataframes in pandas
- allows accessing fields by name

3. **Masked arrays**
- These arrays are useful to deal with datasets containing missing values, invalid data or placeholder

4. **Metrix**

**datatypes used in structured arrays**

1. Datatype - ':' or **'i4'** , python datatype equivalent - **int** , example - ('num','i4')
2. Datatype - **'U10'** , python datatype equivalent - **str** , example - ('name','U10')
3. Datatype - 'f' or **'f8'** , python datatype equivalent - **float** , example - ('nums','f8')
4. Datatype -  **'bool'** , python datatype equivalent - **boolean** , example - ('accepted','bool')

**Vectors** (1-D array)
- vectors are one-dimensional array(1-D array) which stores data usually in list format

**Matrix(2-D tensor)**
- it is 2-D tensor that is arrays with rows and columns

**Tensor** (N-D array)
- tensor are arrays with 3 or more dimension

In [3]:
import numpy as np

In [4]:
a = np.array([1,23,4,1]) # creating 1 dimensional array
print(a)

[ 1 23  4  1]


In [200]:
a.shape

(4, 2)

In [6]:
a.ndim

1

In [7]:
# creating 2 dimensional array
b = np.array([[1,2],[4,5]])
print(b)

[[1 2]
 [4 5]]


In [8]:
b.shape

(2, 2)

In [9]:
b.ndim

2

In [10]:
# creating 3 dimensional array or tensor
c = np.array([[[2,4],[6,8],[9,10],[56,43]]])
print(c)

[[[ 2  4]
  [ 6  8]
  [ 9 10]
  [56 43]]]


In [11]:
print(c.shape)

(1, 4, 2)


In [12]:
c.ndim # check which dimensional array is

3

**Structured array**

In [14]:
# creating structured arrays - records are on the form of rows and columns
dtype = ([('id','i4'),('name', 'U10'),('marks','f8')])
d1 = np.array([(1,"mohini",6.7),(2,"bhargavi",7.8),(3,"gauri",8.9)],dtype=dtype)

print(d1['name'][1]) # accessing the feature via column name and row index

bhargavi


In [15]:
print(d1) # accessing all the elements of the structured array

[(1, 'mohini', 6.7) (2, 'bhargavi', 7.8) (3, 'gauri', 8.9)]


In [16]:
# accessing the columns in structured array
print(d1['id'])
print(d1['name'])
print(d1['marks'])

[1 2 3]
['mohini' 'bhargavi' 'gauri']
[6.7 7.8 8.9]


In [17]:
# will show datatypes of each column
print(d1.dtype)

[('id', '<i4'), ('name', '<U10'), ('marks', '<f8')]


In [18]:
# for creating zeros array
d = np.zeros((2,3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
d.ndim

2

In [20]:
d.shape

(2, 3)

In [21]:
# want to create array have value only 1
e = np.ones((3,5))
print(e)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Identity matrix creation**

In [23]:
f = np.eye(3) # creating identity matrix
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# creates an array with evenly spaced values specified in range
g = np.arange(1,10,2)
print(g)

[1 3 5 7 9]


In [25]:
# creates array of evenly spaced numbers(specified interval - (displays in float))
h = np.linspace(0,2,5) 
print(h)

[0.  0.5 1.  1.5 2. ]


In [26]:
# specified number of elements
h.size

5

# Assignment 1

1. create a 2D array of shape(3,4) filled with all ones

In [28]:
m = np.ones((3,4))
print(m)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


2. create 1D numpy array with values from 10 to 50 with a step of 4

In [30]:
n = np.arange(10,50,4)
print(n)

[10 14 18 22 26 30 34 38 42 46]


3. create a 4x4 identity matrix

In [32]:
p = np.eye(4)
print(p)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


4. create an array with 5 values evenly spaced between 0 and 1

In [34]:
q = np.linspace(0,1,5)
print(q)

[0.   0.25 0.5  0.75 1.  ]


5. create a 1d numpy array with values from 10 to 50 with a step of 5

In [36]:
r = np.arange(10,50,5)
print(r)

[10 15 20 25 30 35 40 45]


6. create a 3x3 array with random integers between 10 and 99

In [67]:
# random number methods
u = np.random.rand(5)
print(u)

[0.98688649 0.79579984 0.94687855 0.50223094 0.05595777]


7. create an array of shape(2,3) filled with zeros and another filled with sevens

In [41]:
s = np.zeros((2,3))
print(s)
# full - create an array of fiven shape and fills with specified values
t = np.full((2,3),7)
t

[[0. 0. 0.]
 [0. 0. 0.]]


array([[7, 7, 7],
       [7, 7, 7]])

8. create an array with values from 1 to 12 and reshape it to a 3x4 matrix

In [44]:
t = np.arange(1,13)
print(t)
# t= np.reshape((3,4))
re_shape = t.reshape(3,4)
print(re_shape)
re_shape.shape

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(3, 4)

9. create a 2D array of shape(5,2) and display
- number of dimensions
- shape
- total number of elements
- data type

In [47]:
arr = np.array([[2,4],[5,6],[7,6],[8,7],[9,0]])
print(arr)
# number of dimension
arr.ndim


[[2 4]
 [5 6]
 [7 6]
 [8 7]
 [9 0]]


2

In [49]:
# shape
arr.shape

(5, 2)

In [51]:
# number of elements
arr.size

10

In [53]:
# datatype
arr.dtype

dtype('int32')

10. create a 2D array and access:
- the first row
- the second column
- the last element

In [56]:
array_2d = np.array([[1,2],[3,4]])
print(array_2d)

[[1 2]
 [3 4]]


In [58]:
# first row
array_2d[0]

array([1, 2])

In [60]:
# second column
array_2d[1]

array([3, 4])

In [62]:
# last element
array_2d[(1,1)]

4

In [74]:
#np.random.randint() - generates an array of the given size and the numbers in th range

c = np.random.randint(10,99,(3,3))
print(c)

[[74 70 71]
 [70 12 79]
 [33 25 74]]


In [76]:
d = np.random.randn(3,3)
d

array([[ 1.38367584, -0.84621962, -1.46143637],
       [ 1.66946613, -0.48554976,  0.99501809],
       [-1.08450996, -0.05293416,  0.66383823]])

In [78]:
e = np.random.randn(7) + 10 # 10 is mean
print(e)

[ 9.47584714 11.34359749  9.76538072 10.29946191  9.61805032 11.74707948
 11.07018407]


In [90]:
# mathematical operations of array

# np.sum() - returns the total(sum) of all the elements

f = np.array([2,4,6,8])
print(f)
print(np.sum(f))

# np.mean() - return the mean(average) of all the items in the array
print(np.mean(f))

# np.std() - returns the standard deviation of all the items in the array
print(np.std(f))

# np.max and np.min
print(np.max(f))
print(np.min(f))

# np.argmin and np.argmax - retuens the index value of max and min values
print(np.argmin(f))
print(np.argmax(f))

[2 4 6 8]
20
5.0
2.23606797749979
8
2
0
3


**Array manipulation**


In [116]:
g = np.array([78,1220,30,40,67,40,50,123,145,654,678])
print(g)

# np.sort() - returns sorted values in the array
print(np.sort(g))

# np.unique() - returns an array with sorted and unique elements
print(np.unique(g))

h = np.array([45,65,78,10,33,98])
print(h)

# np.concatenate() - returns the merged arrays , can join two or more than two arrays
i= np.concatenate((g,h))
print(i)
print(np.sort(i))

[  78 1220   30   40   67   40   50  123  145  654  678]
[  30   40   40   50   67   78  123  145  654  678 1220]
[  30   40   50   67   78  123  145  654  678 1220]
[45 65 78 10 33 98]
[  78 1220   30   40   67   40   50  123  145  654  678   45   65   78
   10   33   98]
[  10   30   33   40   40   45   50   65   67   78   78   98  123  145
  654  678 1220]


# Assignment 2

1. create 1D array of numbers from 0 to 9

In [16]:
import numpy as np


In [18]:
a = np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


2. find the mean , median,standard deviation and sum of elements in an array

In [21]:
print(np.mean(a))

4.5


In [23]:
print(np.median(a))

4.5


In [25]:
print(np.std(a))

2.8722813232690143


In [27]:
print(np.sum(a))

45


3. Find the maximum and minimum values in an array and their indices.

In [30]:
print(np.max(a))

9


In [32]:
print(np.min(a))

0


In [34]:
print(np.argmax(a))

9


In [36]:
print(np.argmin(a))

0


4. Generate a 1D array of 10 random integers between 1 and 100.

In [68]:
b = np.random.randint(1,100,(10))
print(b)

[35  1 79 65 69 63 12 42 97 84]


5. Create a 3x3 array of random floats.

In [75]:
c = np.random.randn(3,3)
print(c)

[[ 0.08532143 -0.52942418  1.50070776]
 [-0.16199814  0.29386741 -1.87446695]
 [ 0.91045522  0.91023321  1.08472124]]


6. Generate 1000 samples from a normal distribution and compute mean and std.

In [86]:
d = np.random.randint(1,5000,(1000))
print(d)

[1331  620 1898 2033  682  698 3698 2202  678 2289 4589 4160 3541 4317
  426 4668 2270 1705 3706  171 3506 4168 4352 4483 2707 2380 3955 2859
 1233 1270 4508  410 3818 4415 3710 1113 1781 2462 3883 3161 4952 1275
 1709 2497  720 2793 4540 3767 1636 2922   61 3632 3892 2189 4471 1340
 1500 4945 4118 4539 4267 1320 3328 1151 2822 4708 4523 1595 2425  146
 2592 3644 4197 1725  554  129 1189  649 1523 4463 1701 1204 4794 3203
 3949 1200 2891  129  918 2387 4266 1794 1361 4164 1837 3637 2438 1555
 4290 3544  680 4170    4 2413 3131  877 3344 3947 2209 2825 4193 1594
  675 1330 3364 4422 4398 2603 2480 1817 1540 3146 3232 3274 2963 2825
 3915 1120 3254  441  511 1746 1428 2833 2260 2467 1997 3015 4528 3689
  630 2963 2500 1362 1917  679 2129 3776 3633 2414  382  497 4517  884
 2413  543   49 2017 4231 2957  335 3051 3910 3637 1997 2163 3882 2494
 2334 3935 2363 3355 1824  190 4513 4826 3383  258 4864  986 1182 2514
  266  704 3804  624 1032  877 1688 1913 3894  821 4806 2514 2969 3355
 3195 

In [88]:
print(np.mean(d))

2438.929


In [90]:
print(np.std(d))

1458.5772409985698


7. Get unique values from an array and their counts.

In [93]:
e = np.array([11,23,11,45,32,65,78,21,55,65,87,90,21])
print(e)

[11 23 11 45 32 65 78 21 55 65 87 90 21]


In [95]:
print(np.unique(e))

[11 21 23 32 45 55 65 78 87 90]


8. Generate a 2D array of shape (5, 5) from a normal distribution with mean=50 and std=10.

In [108]:
f = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(f)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [110]:
f.shape

(5, 5)

In [112]:
print(f + 50)

[[51 52 53 54 55]
 [56 57 58 59 60]
 [61 62 63 64 65]
 [66 67 68 69 70]
 [71 72 73 74 75]]


In [114]:
f + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

9. create a numpy array of even numbers between 2 and 20

In [120]:
even = np.arange(2,20,(2))
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

10. Find the shape, size, and data type of the array a = np.array([[1, 2], [3, 4]]).

In [123]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [125]:
a.shape

(2, 2)

In [127]:
a.size

4

In [137]:
a.dtype

dtype('int32')

11. Generate a 1D array of 5 random numbers between 0 and 1.

In [152]:
g = np.random.randint(0,1,(5))
print(g)

[0 0 0 0 0]


In [154]:
g = np.random.rand(5)

In [156]:
g

array([0.39782965, 0.1441615 , 0.62040466, 0.33517896, 0.39359235])

12. Find the maximum, minimum, and sum of elements in the array [5, 8, 2, 9, 1].

In [159]:
h = np.array([5,8,2,9,1])
print(h)

[5 8 2 9 1]


In [161]:
print(np.max(h))

9


In [163]:
print(np.min(h))

1


In [165]:
print(np.sum(h))

25


13. Get the first 3 elements from the array [10, 20, 30, 40, 50].

In [170]:
array1 = np.array([10,20,30,40,50])
print(array1)

[10 20 30 40 50]


In [178]:
array1[:3]

array([10, 20, 30])

# **Matrix operations**

In [2]:
import numpy as np

In [20]:
a = np.array([[3,4],[5,6]]) # matrix 1
b = np.array([[10,12],[3,6]]) # matrix 2
print(a)
print(b)

[[3 4]
 [5 6]]
[[10 12]
 [ 3  6]]


In [22]:
print(a + b) # addition

[[13 16]
 [ 8 12]]


In [24]:
print(a - b) # subtraction

[[-7 -8]
 [ 2  0]]


In [26]:
print(a * b) # multiplication

[[30 48]
 [15 36]]


In [28]:
print(np.dot(a,b)) # matrix dot product

[[42 60]
 [68 96]]


In [30]:
print(a.T) # transpose of a

[[3 5]
 [4 6]]


In [32]:
print(b.T) # transpose of b

[[10  3]
 [12  6]]


In [34]:
from numpy.linalg import det # important to import if using determinant
print(det(a)) # matrix determinant

-2.0000000000000004


In [36]:
# dot product of matrix and vector
A = np.array([[1,3],[4,5]]) # 2D array
V = np.array([2,3]) # 1D array

print('Matrix A is: \n',A)
print('Vector V is: \n',V)

print('Dot product is : \n',np.dot(A,V))

Matrix A is: 
 [[1 3]
 [4 5]]
Vector V is: 
 [2 3]
Dot product is : 
 [11 23]


**Random Sampling** : randomly picks values from a given array

In [59]:
c = np.array([1,2,3,4,5,6,7,8,9,10])
d = np.random.choice(c,size = 5)
print(d)

e = np.array([[3,4,5],[6,7,8]])
f = np.random.choice(e.flatten(),size = 5,replace = False) # flatten() - converts 2d array in 1d and replace = False will not repeat any value
print(f)

# .shape[] selects row randomly
r = np.random.choice(e.shape[0], size = 2, replace = False) 
print(r)

# randomly selects column
col = np.random.choice(e.shape[1], size = 2, replace = False)
print(e[:,col])
print(e[r])

[1 2 2 9 4]
[3 6 5 4 7]
[0 1]
[[5 3]
 [8 6]]
[[3 4 5]
 [6 7 8]]


**Random shuffling** - change array elements positions randomly

In [67]:
g = np.array([2,4,6,8,10])
print(g)
np.random.shuffle(g)
print(g)

# random shuffling on 2d array
h = np.array([[2,4,6],[1,2,3],[7,8,9]])
print(h)
np.random.shuffle(h)
print(h)

[ 2  4  6  8 10]
[10  6  2  4  8]
[[2 4 6]
 [1 2 3]
 [7 8 9]]
[[1 2 3]
 [7 8 9]
 [2 4 6]]


**Comparison in array**

In [195]:
i = np.array([1,2,3])
j = np.array([4,5,6])
print(i == j)
print(i != j)
print(i >= j)
print(i <= j)
print(i > j)
print(i < j)


[False False False]
[ True  True  True]
[False False False]
[ True  True  True]
[False False False]
[ True  True  True]


# Assignment 3

1. Given two arrays add , subtract , multiply them element - wise

In [85]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


2. Create two 2×2 NumPy arrays and perform matrix addition.


In [90]:
matrix1 = np.array([[12,10],[6,9]])
matrix2 = np.array([[4,67],[10,31]])
print(matrix1)
print(matrix2)
print(matrix1 + matrix2)

[[12 10]
 [ 6  9]]
[[ 4 67]
 [10 31]]
[[16 77]
 [16 40]]


3. Create a 2×3 matrix and a 3×2 matrix, then perform matrix multiplication using NumPy.


In [95]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[6,5],[9,1]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [6 5]
 [9 1]]


In [101]:
print(np.dot(a,b))

[[40 15]
 [88 39]]


4. Create two 3×3 matrices and subtract the second from the first.


In [104]:
a = np.array([[[1,34,21],[56,88,10]]])
b = np.array([[[36,12,18],[56,43,21]]])
print(a)
print(b)

[[[ 1 34 21]
  [56 88 10]]]
[[[36 12 18]
  [56 43 21]]]


In [110]:
print(a-b)

[[[-35  22   3]
  [  0  45 -11]]]


5. Create a 1D array with values from 10 to 20. Randomly pick 3 elements without replacement.


In [115]:
arr = np.arange(10,20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [117]:
r = np.random.choice(arr,size = 3,replace = False)

In [119]:
r

array([14, 17, 11])

6. Create a 4×3 matrix. Randomly select one of the rows.


In [180]:
a = np.array([[1,2,3],[21,4,5],[5,7,6],[32,1,7]])
print(a)
random_row = np.random.choice(a.shape[0],size = 2,replace = False)
print(random_row)

[[ 1  2  3]
 [21  4  5]
 [ 5  7  6]
 [32  1  7]]
[0 2]


7. Create an array with values from 1 to 10 and shuffle it in place.


In [159]:
a = np.arange(1,10)
print(a)
np.random.shuffle(a)
print(a)

[1 2 3 4 5 6 7 8 9]
[2 8 4 3 6 1 9 5 7]


8. Create two 2×2 matrices and return a boolean matrix where the first is greater than the second.


In [162]:
m1 = ([[1,2],[4,5]])
m2 = ([[67,1],[8,10]])
print(m1 > m2)

False


9. Create a 3×3 matrix with random integers (0–20). Count how many elements are greater than 10.


In [167]:
m = np.random.randint(0,20,(3,3))
print(m)

[[15 19 14]
 [ 7 11  6]
 [ 8  5  5]]


In [177]:
print(m > 10)

[[ True  True  True]
 [False  True False]
 [False False False]]


10. Convert a 2D array to a 1D array (flatten it).

In [188]:
a = np.array([[1,2],[21,4],[5,7],[32,1]])
print(a)
b = np.random.choice(a.flatten(),size = 10)
print(b)

[[ 1  2]
 [21  4]
 [ 5  7]
 [32  1]]
[32  4 32  1  5  2  4  4  7 21]
