# **Numpy** (numerical python)
- It stand for numerical python.
- it is used for numerical computation
- it provide support for large multi-dimensional arrays and matrices along with a collection of highe-level mathematical function to operates on these arrays.

**features of NumPy**
1. **supports operation on N-dimensional arrays** - N-dimensional array also known as (n-D array) is a core data structure used in numpy for efficient storage and computation.
2. **numpy allows broadcasting** i.e. arithematic operation on arrays of different shapes.
3. **numpy also allow vectorization** i.e. eliminating needs for loops during operations on array.
4. Numpy provides built-in support for linear algebra, statistics, trigonometry calculation
5. numpy can be integrated with other python libraries like pandas, matplotlib, seaborn, scikit learn etc.

**Data structure in numpy**

- numpy primerily words with single core data structure. n-D array
1. **n-dimensional array**
- This can be of any (N) dimensions
- N-D array can represent vectors (1D array) matrices (2D array) or tensors (3-D array)
- N-D array are homogeneous which means all elements value in N-D array must be of same datatype
- this array are of fixed size , once created we cannot change size of array

2. **Structured array**
- These arrays are **heterogeneous** arrays i.e. used to handle , store data of different datatypes similar to SQL, dataframes in pandas
- allows accessing fields by name

3. **Masked arrays**
- These arrays are useful to deal with datasets containing missing values, invalid data or placeholder

4. **Metrix**

**datatypes used in structured arrays**

1. Datatype - ':' or **'i4'** , python datatype equivalent - **int** , example - ('num','i4')
2. Datatype - **'U10'** , python datatype equivalent - **str** , example - ('name','U10')
3. Datatype - 'f' or **'f8'** , python datatype equivalent - **float** , example - ('nums','f8')
4. Datatype -  **'bool'** , python datatype equivalent - **boolean** , example - ('accepted','bool')

**Vectors** (1-D array)
- vectors are one-dimensional array(1-D array) which stores data usually in list format

**Matrix(2-D tensor)**
- it is 2-D tensor that is arrays with rows and columns

**Tensor** (N-D array)
- tensor are arrays with 3 or more dimension

In [1]:
import numpy as np

In [4]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [5]:
a = np.array([1,23,4,1]) # creating 1 dimensional array
print(a)

[ 1 23  4  1]


In [6]:
a.shape

(4,)

In [7]:
a.ndim

1

In [8]:
# creating 2 dimensional array
b = np.array([[1,2],[4,5]])
print(b)

[[1 2]
 [4 5]]


In [9]:
b.shape

(2, 2)

In [10]:
b.ndim

2

In [11]:
# creating 3 dimensional array or tensor
c = np.array([[[2,4],[6,8],[9,10],[56,43]]])
print(c)

[[[ 2  4]
  [ 6  8]
  [ 9 10]
  [56 43]]]


In [12]:
print(c.shape)

(1, 4, 2)


In [13]:
c.ndim # check which dimensional array is

3

**Structured array**

In [15]:
# creating structured arrays - records are on the form of rows and columns
dtype = ([('id','i4'),('name', 'U10'),('marks','f8')])
d1 = np.array([(1,"mohini",6.7),(2,"bhargavi",7.8),(3,"gauri",8.9)],dtype=dtype)

print(d1['name'][1]) # accessing the feature via column name and row index

bhargavi


In [16]:
print(d1) # accessing all the elements of the structured array

[(1, 'mohini', 6.7) (2, 'bhargavi', 7.8) (3, 'gauri', 8.9)]


In [17]:
# accessing the columns in structured array
print(d1['id'])
print(d1['name'])
print(d1['marks'])

[1 2 3]
['mohini' 'bhargavi' 'gauri']
[6.7 7.8 8.9]


In [18]:
# will show datatypes of each column
print(d1.dtype)

[('id', '<i4'), ('name', '<U10'), ('marks', '<f8')]


In [19]:
# for creating zeros array
d = np.zeros((2,3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
d.ndim

2

In [21]:
d.shape

(2, 3)

In [22]:
# want to create array have value only 1
e = np.ones((3,5))
print(e)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Identity matrix creation**

In [24]:
f = np.eye(3) # creating identity matrix
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# creates an array with evenly spaced values specified in range
g = np.arange(1,10,2)
print(g)

[1 3 5 7 9]


In [26]:
# creates array of evenly spaced numbers(specified interval - (displays in float))
h = np.linspace(0,2,5) 
print(h)

[0.  0.5 1.  1.5 2. ]


In [27]:
# specified number of elements
h.size

5

# Assignment 1

1. create a 2D array of shape(3,4) filled with all ones

In [30]:
m = np.ones((3,4))
print(m)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


2. create 1D numpy array with values from 10 to 50 with a step of 4

In [32]:
n = np.arange(10,50,4)
print(n)

[10 14 18 22 26 30 34 38 42 46]


3. create a 4x4 identity matrix

In [34]:
p = np.eye(4)
print(p)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


4. create an array with 5 values evenly spaced between 0 and 1

In [36]:
q = np.linspace(0,1,5)
print(q)

[0.   0.25 0.5  0.75 1.  ]


5. create a 1d numpy array with values from 10 to 50 with a step of 5

In [38]:
r = np.arange(10,50,5)
print(r)

[10 15 20 25 30 35 40 45]


6. create a 3x3 array with random integers between 10 and 99

In [40]:
# random number methods
u = np.random.rand(5)
print(u)

[0.10047169 0.06953096 0.13301521 0.74291142 0.1265844 ]


7. create an array of shape(2,3) filled with zeros and another filled with sevens

In [42]:
s = np.zeros((2,3))
print(s)
# full - create an array of fiven shape and fills with specified values
t = np.full((2,3),7)
t

[[0. 0. 0.]
 [0. 0. 0.]]


array([[7, 7, 7],
       [7, 7, 7]])

8. create an array with values from 1 to 12 and reshape it to a 3x4 matrix

In [44]:
t = np.arange(1,13)
print(t)
# t= np.reshape((3,4))
re_shape = t.reshape(3,4)
print(re_shape)
re_shape.shape

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(3, 4)

9. create a 2D array of shape(5,2) and display
- number of dimensions
- shape
- total number of elements
- data type

In [46]:
arr = np.array([[2,4],[5,6],[7,6],[8,7],[9,0]])
print(arr)
# number of dimension
arr.ndim


[[2 4]
 [5 6]
 [7 6]
 [8 7]
 [9 0]]


2

In [47]:
# shape
arr.shape

(5, 2)

In [48]:
# number of elements
arr.size

10

In [49]:
# datatype
arr.dtype

dtype('int32')

10. create a 2D array and access:
- the first row
- the second column
- the last element

In [51]:
array_2d = np.array([[1,2],[3,4]])
print(array_2d)

[[1 2]
 [3 4]]


In [52]:
# first row
array_2d[0]

array([1, 2])

In [53]:
# second column
array_2d[1]

array([3, 4])

In [54]:
# last element
array_2d[(1,1)]

4

In [55]:
#np.random.randint() - generates an array of the given size and the numbers in th range

c = np.random.randint(10,99,(3,3))
print(c)

[[60 88 73]
 [89 25 49]
 [93 26 22]]


In [56]:
d = np.random.randn(3,3)
d

array([[ 0.72731354, -1.00855652,  0.98373154],
       [ 0.9403978 ,  0.11118616, -0.297104  ],
       [-0.46431214,  0.41112328,  0.46171853]])

In [57]:
e = np.random.randn(7) + 10 # 10 is mean
print(e)

[ 9.51570354  9.38553521 10.71810045 10.60480311  7.61609019 10.83695106
 10.16106354]


In [58]:
# mathematical operations of array

# np.sum() - returns the total(sum) of all the elements

f = np.array([2,4,6,8])
print(f)
print(np.sum(f))

# np.mean() - return the mean(average) of all the items in the array
print(np.mean(f))

# np.std() - returns the standard deviation of all the items in the array
print(np.std(f))

# np.max and np.min
print(np.max(f))
print(np.min(f))

# np.argmin and np.argmax - retuens the index value of max and min values
print(np.argmin(f))
print(np.argmax(f))

[2 4 6 8]
20
5.0
2.23606797749979
8
2
0
3


**Array manipulation**


In [60]:
g = np.array([78,1220,30,40,67,40,50,123,145,654,678])
print(g)

# np.sort() - returns sorted values in the array
print(np.sort(g))

# np.unique() - returns an array with sorted and unique elements
print(np.unique(g))

h = np.array([45,65,78,10,33,98])
print(h)

# np.concatenate() - returns the merged arrays , can join two or more than two arrays
i= np.concatenate((g,h))
print(i)
print(np.sort(i))

[  78 1220   30   40   67   40   50  123  145  654  678]
[  30   40   40   50   67   78  123  145  654  678 1220]
[  30   40   50   67   78  123  145  654  678 1220]
[45 65 78 10 33 98]
[  78 1220   30   40   67   40   50  123  145  654  678   45   65   78
   10   33   98]
[  10   30   33   40   40   45   50   65   67   78   78   98  123  145
  654  678 1220]


# Assignment 2

1. create 1D array of numbers from 0 to 9

In [63]:
import numpy as np


In [64]:
a = np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


2. find the mean , median,standard deviation and sum of elements in an array

In [66]:
print(np.mean(a))

4.5


In [67]:
print(np.median(a))

4.5


In [68]:
print(np.std(a))

2.8722813232690143


In [69]:
print(np.sum(a))

45


3. Find the maximum and minimum values in an array and their indices.

In [71]:
print(np.max(a))

9


In [72]:
print(np.min(a))

0


In [73]:
print(np.argmax(a))

9


In [74]:
print(np.argmin(a))

0


4. Generate a 1D array of 10 random integers between 1 and 100.

In [76]:
b = np.random.randint(1,100,(10))
print(b)

[54 99 83 36 34 14 68 44 89 67]


5. Create a 3x3 array of random floats.

In [78]:
c = np.random.randn(3,3)
print(c)

[[ 0.36529758 -0.46997722 -1.45401448]
 [ 0.194521    0.29952588 -0.72883601]
 [-1.04612942  0.58976682  1.13590777]]


6. Generate 1000 samples from a normal distribution and compute mean and std.

In [80]:
d = np.random.randint(1,5000,(1000))
print(d)

[2008 3001 1785 3767 3004 2506 1523  549  979  794 1764 4542  147 1263
 4013 3486 1665 1586  228 1472 1730 2524  229 1559 3173 2596  588 1992
 1010 3719  806 1857   67 4299 3432 2075 1949 1253 3878  902 2552 4723
 4792 1633 4079 3578 4461 2789 2478  586 1687 2462  316 2985 1777 4601
 4288 2806 2996 1720  219 2018 2160 2211 3695 3410  678 3095 2526 4460
 4329 1291 4626 1791 2337 4757 4506 3660 2261 1355 3156  823 2514 2356
  201 2950 4251 2253  860 2773 3599 4873  137 2981 4157 3990 3578  952
 3316 2534  969 3892 3926 3035 3505 3822 1851  522 4937 4254  325  965
 1730    6 1278 3018  958 2676 2996 4062  188 3244 3580 3680  491 1447
 3405 4233 1636 4782 2948 2264 4992 4549 2166 1019 3775 3890 2654 4258
 2304 3461 1335  593 3900 1957 1756  351 1489 2338  880 1346  649 2796
 1768  740  817 2324  335 2975 2800 4689 4528 4334  532  545 4221 2361
 3353 1850 3592  618   54  773 4938  180 3137 2454 2334 1794 3826 4244
 4755 2182 1978 1248 4987 1036 1018 2707 2927  184  267 3826 3147 2815
 2246 

In [81]:
print(np.mean(d))

2481.864


In [82]:
print(np.std(d))

1410.8700973172547


7. Get unique values from an array and their counts.

In [84]:
e = np.array([11,23,11,45,32,65,78,21,55,65,87,90,21])
print(e)

[11 23 11 45 32 65 78 21 55 65 87 90 21]


In [85]:
print(np.unique(e))

[11 21 23 32 45 55 65 78 87 90]


8. Generate a 2D array of shape (5, 5) from a normal distribution with mean=50 and std=10.

In [87]:
f = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(f)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [88]:
f.shape

(5, 5)

In [89]:
print(f + 50)

[[51 52 53 54 55]
 [56 57 58 59 60]
 [61 62 63 64 65]
 [66 67 68 69 70]
 [71 72 73 74 75]]


In [90]:
f + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

9. create a numpy array of even numbers between 2 and 20

In [92]:
even = np.arange(2,20,(2))
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

10. Find the shape, size, and data type of the array a = np.array([[1, 2], [3, 4]]).

In [94]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [95]:
a.shape

(2, 2)

In [96]:
a.size

4

In [97]:
a.dtype

dtype('int32')

11. Generate a 1D array of 5 random numbers between 0 and 1.

In [99]:
g = np.random.randint(0,1,(5))
print(g)

[0 0 0 0 0]


In [100]:
g = np.random.rand(5)

In [101]:
g

array([0.52736388, 0.44264532, 0.55491352, 0.99861918, 0.66864486])

12. Find the maximum, minimum, and sum of elements in the array [5, 8, 2, 9, 1].

In [103]:
h = np.array([5,8,2,9,1])
print(h)

[5 8 2 9 1]


In [104]:
print(np.max(h))

9


In [105]:
print(np.min(h))

1


In [106]:
print(np.sum(h))

25


13. Get the first 3 elements from the array [10, 20, 30, 40, 50].

In [108]:
array1 = np.array([10,20,30,40,50])
print(array1)

[10 20 30 40 50]


In [109]:
array1[:3]

array([10, 20, 30])

# **Matrix operations**

In [111]:
import numpy as np

In [112]:
a = np.array([[3,4],[5,6]]) # matrix 1
b = np.array([[10,12],[3,6]]) # matrix 2
print(a)
print(b)

[[3 4]
 [5 6]]
[[10 12]
 [ 3  6]]


In [113]:
print(a + b) # addition

[[13 16]
 [ 8 12]]


In [114]:
print(a - b) # subtraction

[[-7 -8]
 [ 2  0]]


In [115]:
print(a * b) # multiplication

[[30 48]
 [15 36]]


In [116]:
print(np.dot(a,b)) # matrix dot product

[[42 60]
 [68 96]]


In [117]:
print(a.T) # transpose of a

[[3 5]
 [4 6]]


In [118]:
print(b.T) # transpose of b

[[10  3]
 [12  6]]


In [119]:
from numpy.linalg import det # important to import if using determinant
print(det(a)) # matrix determinant

-2.0000000000000004


In [120]:
# dot product of matrix and vector
A = np.array([[1,3],[4,5]]) # 2D array
V = np.array([2,3]) # 1D array

print('Matrix A is: \n',A)
print('Vector V is: \n',V)

print('Dot product is : \n',np.dot(A,V))

Matrix A is: 
 [[1 3]
 [4 5]]
Vector V is: 
 [2 3]
Dot product is : 
 [11 23]


**Random Sampling** : randomly picks values from a given array

In [122]:
c = np.array([1,2,3,4,5,6,7,8,9,10])
d = np.random.choice(c,size = 5)
print(d)

e = np.array([[3,4,5],[6,7,8]])
f = np.random.choice(e.flatten(),size = 5,replace = False) # flatten() - converts 2d array in 1d and replace = False will not repeat any value
print(f)

# .shape[] selects row randomly
r = np.random.choice(e.shape[0], size = 2, replace = False) 
print(r)

# randomly selects column
col = np.random.choice(e.shape[1], size = 2, replace = False)
print(e[:,col])
print(e[r])

[3 6 1 2 6]
[6 4 7 3 5]
[1 0]
[[4 5]
 [7 8]]
[[6 7 8]
 [3 4 5]]


**Random shuffling** - change array elements positions randomly

In [124]:
g = np.array([2,4,6,8,10])
print(g)
np.random.shuffle(g)
print(g)

# random shuffling on 2d array
h = np.array([[2,4,6],[1,2,3],[7,8,9]])
print(h)
np.random.shuffle(h)
print(h)

[ 2  4  6  8 10]
[ 4  2  8  6 10]
[[2 4 6]
 [1 2 3]
 [7 8 9]]
[[1 2 3]
 [2 4 6]
 [7 8 9]]


**Comparison in array**

In [126]:
i = np.array([1,2,3])
j = np.array([4,5,6])
print(i == j)
print(i != j)
print(i >= j)
print(i <= j)
print(i > j)
print(i < j)


[False False False]
[ True  True  True]
[False False False]
[ True  True  True]
[False False False]
[ True  True  True]


# Assignment 3

1. Given two arrays add , subtract , multiply them element - wise

In [129]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


2. Create two 2×2 NumPy arrays and perform matrix addition.


In [131]:
matrix1 = np.array([[12,10],[6,9]])
matrix2 = np.array([[4,67],[10,31]])
print(matrix1)
print(matrix2)
print(matrix1 + matrix2)

[[12 10]
 [ 6  9]]
[[ 4 67]
 [10 31]]
[[16 77]
 [16 40]]


3. Create a 2×3 matrix and a 3×2 matrix, then perform matrix multiplication using NumPy.


In [133]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[6,5],[9,1]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [6 5]
 [9 1]]


In [134]:
print(np.dot(a,b))

[[40 15]
 [88 39]]


4. Create two 3×3 matrices and subtract the second from the first.


In [136]:
a = np.array([[[1,34,21],[56,88,10]]])
b = np.array([[[36,12,18],[56,43,21]]])
print(a)
print(b)

[[[ 1 34 21]
  [56 88 10]]]
[[[36 12 18]
  [56 43 21]]]


In [137]:
print(a-b)

[[[-35  22   3]
  [  0  45 -11]]]


5. Create a 1D array with values from 10 to 20. Randomly pick 3 elements without replacement.


In [139]:
arr = np.arange(10,20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [140]:
r = np.random.choice(arr,size = 3,replace = False)

In [141]:
r

array([17, 16, 11])

6. Create a 4×3 matrix. Randomly select one of the rows.


In [143]:
a = np.array([[1,2,3],[21,4,5],[5,7,6],[32,1,7]])
print(a)
random_row = np.random.choice(a.shape[0],size = 2,replace = False)
print(random_row)

[[ 1  2  3]
 [21  4  5]
 [ 5  7  6]
 [32  1  7]]
[3 2]


7. Create an array with values from 1 to 10 and shuffle it in place.


In [145]:
a = np.arange(1,10)
print(a)
np.random.shuffle(a)
print(a)

[1 2 3 4 5 6 7 8 9]
[9 2 8 7 6 4 1 5 3]


8. Create two 2×2 matrices and return a boolean matrix where the first is greater than the second.


In [147]:
m1 = ([[1,2],[4,5]])
m2 = ([[67,1],[8,10]])
print(m1 > m2)

False


9. Create a 3×3 matrix with random integers (0–20). Count how many elements are greater than 10.


In [149]:
m = np.random.randint(0,20,(3,3))
print(m)

[[ 4 16  2]
 [10 11  1]
 [ 8  8 12]]


In [150]:
print(m > 10)

[[False  True False]
 [False  True False]
 [False False  True]]


10. Convert a 2D array to a 1D array (flatten it).

In [152]:
a = np.array([[1,2],[21,4],[5,7],[32,1]])
print(a)
b = np.random.choice(a.flatten(),size = 8)
print(b)

[[ 1  2]
 [21  4]
 [ 5  7]
 [32  1]]
[ 1  4  1  7 32  5 32  5]


# Permutation
- **np.random.permutation** - shuffles the elements of the given range or array Returns a new order
- shuffles the elements of a sequence (array or range) to return a new order.
- Doesn't change the original elements.

- **Algorithm** used by numpy for permutation is
  - **Fisher-yates** - for generating random numbers it uses MT19937


- np.random.permutation() returns a re-arranged array (it does not affect the original array)


- **difference between shuffle and permutation in numpy**
1. **In-place modification** - *np.random.shuffle* modifies the original array while *np.random.permutation* returns a new array
2. **Return value** - *np.random.shuffle* returns None while *np.random.permutation* returns the shuffled array
3. **original array** - *np.random.shuffle* changes the original array while *np.random.permutation* leaves it unchanged
4. **usage** - use *np.random.shuffle* for modifying the single array while *np.random.permutation* use for generating multiple shuffled versions

**Shuffling columns in numpy**
- we use permutation() to shuffle columns in numpy

In [154]:
np.random.permutation(15) # generates elements in the given range and shuffles them

array([ 4,  8,  2,  9,  6, 14, 11, 13,  7,  3,  0,  1,  5, 10, 12])

In [155]:
a = np.array([12,1,32,12,43,11,54,21])
np.random.permutation(a)


array([11, 54, 12, 12, 32, 43,  1, 21])

In [156]:
a = np.array([[1,2,3],
             [4,5,6],
              [7,8,9]])
print(a)

# to shuffle columns use np.random.permutation
col_shuffle = a[:,np.random.permutation(a.shape[1])]
print(col_shuffle)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**np.cumsum()** -  will add first element and next element till last element will print it 

In [158]:
a = np.array([2,4,6,8,10])
print(a)
np.cumsum(a) 

b = np.array([[1,2,3],
             [4,5,6],
              [7,8,9]])
print(np.cumsum(b)) # returns flattened array

print(np.cumsum(b,axis=0)) # columnwise addition
print(np.cumsum(b,axis=1)) # row wise addition

[ 2  4  6  8 10]
[ 1  3  6 10 15 21 28 36 45]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


**np.cumprod** - cumulative product

In [160]:
a = np.array([2,4,6,8,10])
print(a)
np.cumprod(a)

[ 2  4  6  8 10]


array([   2,    8,   48,  384, 3840])

In [161]:
b = np.array([[1,2,3],
             [4,5,6],
              [7,8,9]])
print(np.cumprod(b))

print(np.cumprod(b,axis=1)) # row wise multiplication

print(np.cumprod(b,axis=0)) # column wise multiplication

[     1      2      6     24    120    720   5040  40320 362880]
[[  1   2   6]
 [  4  20 120]
 [  7  56 504]]
[[  1   2   3]
 [  4  10  18]
 [ 28  80 162]]


# logical conditions in numpy

In [163]:
a = np.array([1,2,3,4,5,6])
print(np.logical_and(a>2,a<10)) # returns true only if both the conditions are true
print(np.logical_or(a>2,a<10)) # returns true even if one condition is true
print(np.logical_not(a>2)) # returns the inverse output if true -  it will return false, if false it will return true

[False False  True  True  True  True]
[ True  True  True  True  True  True]
[ True  True False False False False]


In [164]:
np.any(a>5) # returns true only if any element meet the specified condition

True

In [165]:
np.all(a<10) # returns true only if all the elements meet the specified condition

True

**filtering data**
- **&** - works same as logical but instead of returning boolean values it returns real values
- **|** - works same as logical but instead of returning boolean values it returns real values

In [167]:
print(a[(a<10) & (a>3)]) # returns the elements that meets both the specified conditions

[4 5 6]


In [168]:
print(a[(a<10) | (a>3)]) # returns the element that meets either one of the specified condition

[1 2 3 4 5 6]


In [169]:
print(a[~(a>5)]) # returns the elements which meets the opposite condition of the specified condition

[1 2 3 4 5]


In [170]:
print(np.where(a>3)) # returns the indice / index of the elements which meet the specified condition

(array([3, 4, 5], dtype=int64),)


In [171]:
d = np.array([10,20,30,40,50])
e = np.array([25,65,32,76,88])

np.where(d > 20, d ,e) # returns the elements based on the condition and the given arrays

array([25, 65, 30, 40, 50])

**statistical methods in array**

In [173]:
a = np.array([2,4,6,7,9]) # for odd number of elements in array it returns the middle element
print(np.median(a))

a = np.array([2,4,6,7,9,10]) # for even number of elements in array it return the average of middle elements
print(np.median(a))



6.0
6.5


In [174]:
c = np.array([[2,4,5],[6,7,8]])
print(np.median(c))
print(c)
print(np.median(c,axis=1)) # returns median of each row
print(np.median(c,axis=0)) # returns median of each column

5.5
[[2 4 5]
 [6 7 8]]
[4. 7.]
[4.  5.5 6.5]


In [175]:
# np.percentile()

a = np.array([1,2,3,4,5,6,7,8])
print(np.percentile(a,25))
print(np.percentile(a,30))

2.75
3.1


In [176]:
# np.quartile
print(np.quantile(a,0.25))
print(np.quantile(a,0.50))
print(np.quantile(a,0.75))

2.75
4.5
6.25


In [177]:
c = np.array([[2,4,5],[6,7,8]])
print('using percentile')
print(np.percentile(c,25))
print(np.percentile(c,50))
print(np.percentile(c,75))
print('using quantile')
print(np.quantile(c,0.25))
print(np.quantile(c,0.50))
print(np.quantile(c,0.75))

print('using percentile')
print('for row')
print(np.percentile(c,25,axis=1))
print(np.percentile(c,50,axis=1))
print(np.percentile(c,75,axis=1))

print('for column')
print(np.percentile(c,25,axis=0))
print(np.percentile(c,50,axis=0))
print(np.percentile(c,75,axis=0))
print('using quantile')
print('for row')
print(np.quantile(c,0.25,axis=1))
print(np.quantile(c,0.50,axis=1))
print(np.quantile(c,0.75,axis=1))
print('for column')
print(np.quantile(c,0.25,axis=0))
print(np.quantile(c,0.50,axis=0))
print(np.quantile(c,0.75,axis=0))


using percentile
4.25
5.5
6.75
using quantile
4.25
5.5
6.75
using percentile
for row
[3.  6.5]
[4. 7.]
[4.5 7.5]
for column
[3.   4.75 5.75]
[4.  5.5 6.5]
[5.   6.25 7.25]
using quantile
for row
[3.  6.5]
[4. 7.]
[4.5 7.5]
for column
[3.   4.75 5.75]
[4.  5.5 6.5]
[5.   6.25 7.25]


In [178]:
# np.var() - dispersion/spread of the data points

print(np.var(a))
print(np.var(c,axis=1))
print(np.var(c,axis=0))
print(np.std(c))

5.25
[1.55555556 0.66666667]
[4.   2.25 2.25]
1.9720265943665387


1. Given arr = np.array([1, 2, 3, 4]),shuffle the array without modifying the original.

In [180]:
arr = np.array([1,2,3,4])
print(arr)
print(np.random.permutation(arr))

[1 2 3 4]
[3 2 1 4]


2. Write a program to:
- Create an array of numbers from 1 to 10.
- Generate a new array that is a randomly permuted version of the original.
- Print both arrays to show that the original is unchanged.

In [182]:
# create array of numbers between 1 to 10
a = np.arange(1,10)
arr = np.random.permutation(a)
print('unchanged array = ',a)
print('shuffled array',arr)

unchanged array =  [1 2 3 4 5 6 7 8 9]
shuffled array [7 6 2 1 3 4 5 9 8]


3. Write a program that:
- Takes a 1D NumPy array of positive integers.
- Calculates and prints:
- The cumulative sum (np.cumsum)
- The cumulative product (np.cumprod)

In [184]:
a = np.array([11,23,14,23,21,6,4,8,1])
print(a)
print('cumulative sum of array = ',np.cumsum(a))
print('cumulative product of array = ',np.cumprod(a))

[11 23 14 23 21  6  4  8  1]
cumulative sum of array =  [ 11  34  48  71  92  98 102 110 111]
cumulative product of array =  [       11       253      3542     81466   1710786  10264716  41058864
 328470912 328470912]


4. Take a 3D array, Write a program to compute:
- Cumulative sum along axis 0
- Cumulative product along axis 1

In [186]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
print('cumulative sum along axis 0 = ',np.cumsum(a,axis = 0))
print('cumulative product along axis 1 = ',np.cumprod(a,axis = 1))


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
cumulative sum along axis 0 =  [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
cumulative product along axis 1 =  [[[  1   2   3]
  [  4  10  18]
  [ 28  80 162]]]


5. Take an array of student scores and Write a program to:
- Print all scores greater than 60 and less than 85.
- Replace all scores less than 50 with 0 using logical indexing.

In [188]:
arr = np.array([67,60,72,66,34,21,98])
print(arr[(arr < 85) & (arr > 60 )])

[67 72 66]


In [189]:
arr[arr < 50] = 0
print('replaced with 0 ',arr)

replaced with 0  [67 60 72 66  0  0 98]


6. Take an array a = [12,15,16,22,21,35,65,70,85,100,40]. Write a program to:
- Compute the median
- Compute the 25th, 50th, and 75th percentiles
- Compute the 0.1, 0.5, and 0.9 quantiles

In [191]:
a = np.array([12,15,16,22,21,35,65,70,85,100,40])
print(a)
print('median of given array = ',np.median(a))
print('percentile : ')
print('25th percentile = ',np.percentile(a,25))
print('50th percentile = ',np.percentile(a,50))
print('75th percentile = ',np.percentile(a,75))
print('Quantiles : ')
print(np.quantile(a,0.1))
print(np.quantile(a,0.5))
print(np.quantile(a,0.9))

[ 12  15  16  22  21  35  65  70  85 100  40]
median of given array =  35.0
percentile : 
25th percentile =  18.5
50th percentile =  35.0
75th percentile =  67.5
Quantiles : 
15.0
35.0
85.0


# Histogram
- histogram indicates how often different values appear in a dataset. It divides the data into bins (**ranges**). It count how many values fall into each bins.
- fewer (less) bins represent broader range but less details whereas more bins represent narrow ranges but more details

In [339]:
d = np.array([0,2,4,6,8,8,7,8,8,5,4,1,9,10])
np.histogram(d,bins='auto')

"""
np.histogram_bin_edges - return the bins edges(range boundries) used in histogram for the given array

bins = "auto" uses houristics method to choose the number of bins. It select between
1.struges' rule
2.FD(freedman - Diaconis) rule.
it select the rule based on the which return fewer bins(to avoid overfitting / noise)
"""

np.histogram_bin_edges(d)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Correlation
- **use correlate()** -computes the cross correlation of two 1-D sequence. deault mode is valid mode

**correlation mode**

a = [2,4,6]
1. valid = 2X3+4X4+6X6 -> one element only
2. same
3. full

In [371]:
a = np.array([4,5,6,7,8])
b = np.array([5,8,1,3,6])
print('full mode',np.correlate(a,b,mode='full'))
print('Same mode',np.correlate(a,b,mode='same'))
print('valid mode',np.correlate(a,b))

full mode [ 24  42  55  97 135 104  94  99  40]
Same mode [ 55  97 135 104  94]
valid mode [135]


# nan methods
- nan stands for **not a number**
- by default data types is float

In [355]:
# l.np.nan()
a = np.array([2,1,np.nan,7,np.nan])
print(a)

# isnan() - return boolean values for each nan values. it will return true
print('checking for missing values : ',np.isnan(a))
print('checking for total number of missing values ',np.isnan(a).sum())

# np.isinf() - check for infinites values in the array range is - infinity to +inifinity
print('checking for infinite values = ',np.isinf(a))
print('checking for total number of infinite ',np.isinf(a).sum())

# isfinite() - checks for finite values in the array
print('checking for finite values = ',np.isfinite(a))
print('checking for total number of finite ',np.isfinite(a).sum())

print(np.nansum(a))
print(np.nanmean(a))
print(np.nanstd(a))
print(np.nanvar(a))
print(np.nanmedian(a))

# handling missing value
# np.nan_to_num() - replace nan with the specified value. if the value isnt specified it replace it with default
print(np.nan_to_num(a, nan=1))

b = np.array([10,20,np.nan,np.inf,50,np.nan,70,80,-np.inf])
print(b)
print('NaN to sum without specifying any values : ',np.nan_to_num(b))
print('NaN to sum with specifying any values : ',np.nan_to_num(b,nan=1,posinf=12,neginf=15))

# filtering nan values
c = np.array([10,20,np.nan,np.inf,50,np.nan,70,80,-np.inf])
print(~np.isnan(c)) # filter out nan values
print(~np.isinf(c)) # filter out infinite values
print(~np.isposinf(c)) # filter out positive infinite
print(~np.isneginf(c)) # filter out neative infinite
print(~np.isfinite(c)) # filter out finite values

[ 2.  1. nan  7. nan]
checking for missing values :  [False False  True False  True]
checking for total number of missing values  2
checking for infinite values =  [False False False False False]
checking for total number of infinite  0
checking for finite values =  [ True  True False  True False]
checking for total number of finite  3
10.0
3.3333333333333335
2.6246692913372702
6.888888888888888
2.0
[2. 1. 1. 7. 1.]
[ 10.  20.  nan  inf  50.  nan  70.  80. -inf]
NaN to sum without specifying any values :  [ 1.00000000e+001  2.00000000e+001  0.00000000e+000  1.79769313e+308
  5.00000000e+001  0.00000000e+000  7.00000000e+001  8.00000000e+001
 -1.79769313e+308]
NaN to sum with specifying any values :  [10. 20.  1. 12. 50.  1. 70. 80. 15.]
[ True  True False  True  True False  True  True  True]
[ True  True  True False  True  True  True  True False]
[ True  True  True False  True  True  True  True  True]
[ True  True  True  True  True  True  True  True False]
[False False  True  True Fals

- **np.convolve()** : blends two sequences together by sliding them one over the other, multiplying and adding them up to make new sequence.
- **modes**
1. valid
2. same
3. full

In [381]:
# convolve - computes discrete linear convolution of two sequences
print('full mode convolve',np.convolve(a,b,mode='full'))
print('Same mode convolve',np.convolve(a,b,mode='same'))
print('valid mode convolve ',np.convolve(a,b,mode='valid'))

full mode convolve [ 20  57  74 100 141 119  65  66  48]
Same mode convolve [ 74 100 141 119  65]
valid mode convolve  [141]


**covariance**

In [10]:
a = np.array([[2,3],[4,5],[6,7]])
print(a)

# co-variance
print('Covariance matrix : ',np.cov(a,rowvar=False)) # rowvar - True treats rows as variables and columns as observations.
                                                    # If False columns are treated as variables and rows as observations

[[2 3]
 [4 5]
 [6 7]]
Covariance matrix :  [[4. 4.]
 [4. 4.]]


# Co-variance

- covariance indicates how two variables vary together.
    - For **positive covariance**, both the variables increase together
    - for **negative covariance**, if one increses the other variable decreases
    - for **no-zero covariance**, the variables dont vary together
 
- In final covariance matrix , the diagonal values are variance and the off diagonal elements are covariance.

In [63]:
# np.append : to add elements to an existing array
a = np.array([2,3,4,5,6,7,8,9])
# add 12,14,16,18
b = np.append(a,[12,14,16,18])
print(b)

c = np.array([[2,4],[5,6]])
print(c)
# add 14,16,18,20
d = np.append(c,[[14,16],[18,20]],axis=1)

print(d)


[ 2  3  4  5  6  7  8  9 12 14 16 18]
[[2 4]
 [5 6]]
[[ 2  4 14 16]
 [ 5  6 18 20]]


In [101]:
# np.resize() - returns new array based on the specified size. It will repeat elements if the size is larger
a = np.array([1,2,3,4])
print(a)
e = np.resize(a,(2,3))
print(e)

[1 2 3 4]
[[1 2 3]
 [4 1 2]]


In [103]:
# np.reshape() - changes / modifies the original array, by changing its shape.
# manadatory :- the shape must contain the all the element of the array, shape and total number of elements should match
# if we use -1 for either dimension it will auto calculate the dimension we can only  use it for 1 dimension
b = np.array([12,3,2,4,5,1])
print(np.reshape(b,(3,2)))


[[12  3]
 [ 2  4]
 [ 5  1]]
