In [1]:
import numpy as np

In [2]:
a = np.array([1,23,4,1]) # creating 1 dimensional array
print(a)

[ 1 23  4  1]


In [3]:
a.shape

(4,)

In [4]:
a.ndim

1

In [5]:
# creating 2 dimensional array
b = np.array([[1,2],[4,5]])
print(b)

[[1 2]
 [4 5]]


In [6]:
b.shape

(2, 2)

In [7]:
b.ndim

2

In [8]:
# creating 3 dimensional array or tensor
c = np.array([[[2,4],[6,8],[9,10],[56,43]]])
print(c)

[[[ 2  4]
  [ 6  8]
  [ 9 10]
  [56 43]]]


In [9]:
print(c.shape)

(1, 4, 2)


In [10]:
c.ndim # check which dimensional array is

3

**Structured array**

In [12]:
# creating structured arrays - records are on the form of rows and columns
dtype = ([('id','i4'),('name', 'U10'),('marks','f8')])
d1 = np.array([(1,"mohini",6.7),(2,"bhargavi",7.8),(3,"gauri",8.9)],dtype=dtype)

print(d1['name'][1]) # accessing the feature via column name and row index

bhargavi


In [13]:
print(d1) # accessing all the elements of the structured array

[(1, 'mohini', 6.7) (2, 'bhargavi', 7.8) (3, 'gauri', 8.9)]


In [14]:
# accessing the columns in structured array
print(d1['id'])
print(d1['name'])
print(d1['marks'])

[1 2 3]
['mohini' 'bhargavi' 'gauri']
[6.7 7.8 8.9]


In [15]:
# will show datatypes of each column
print(d1.dtype)

[('id', '<i4'), ('name', '<U10'), ('marks', '<f8')]


In [16]:
# for creating zeros array
d = np.zeros((2,3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
d.ndim

2

In [18]:
d.shape

(2, 3)

In [19]:
# want to create array have value only 1
e = np.ones((3,5))
print(e)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Identity matrix creation**

In [21]:
f = np.eye(3) # creating identity matrix
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
# creates an array with evenly spaced values specified in range
g = np.arange(1,10,2)
print(g)

[1 3 5 7 9]


In [23]:
# creates array of evenly spaced numbers(specified interval - (displays in float))
h = np.linspace(0,2,5) 
print(h)

[0.  0.5 1.  1.5 2. ]


In [24]:
# specified number of elements
h.size

5

1. create a 2D array of shape(3,4) filled with all ones

In [26]:
m = np.ones((3,4))
print(m)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


2. create 1D numpy array with values from 10 to 50 with a step of 4

In [28]:
n = np.arange(10,50,4)
print(n)

[10 14 18 22 26 30 34 38 42 46]


3. create a 4x4 identity matrix

In [30]:
p = np.eye(4)
print(p)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


4. create an array with 5 values evenly spaced between 0 and 1

In [32]:
q = np.linspace(0,1,5)
print(q)

[0.   0.25 0.5  0.75 1.  ]


5. create a 1d numpy array with values from 10 to 50 with a step of 5

In [34]:
r = np.arange(10,50,5)
print(r)

[10 15 20 25 30 35 40 45]


6. create a 3x3 array with random integers between 10 and 99

In [36]:
s = np.array(3).arange(10,99)

AttributeError: 'numpy.ndarray' object has no attribute 'arange'

7. create an array of shape(2,3) filled with zeros and another filled with sevens

In [84]:
s = np.zeros((2,3))
print(s)
t = np.array((7))
t

[[0. 0. 0.]
 [0. 0. 0.]]


array(7)

8. create an array with values from 1 to 12 and reshape it to a 3x4 matrix

In [94]:
t = np.arange(1,13)
print(t)
# t= np.reshape((3,4))
re_shape = t.reshape(3,4)
print(re_shape)
re_shape.shape

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(3, 4)

9. create a 2D array of shape(5,2) and display
- number of dimensions
- shape
- total number of elements
- data type

In [115]:
arr = np.array([[2,4],[5,6],[7,6],[8,7],[9,0]])
print(arr)
# number of dimension
arr.ndim


[[2 4]
 [5 6]
 [7 6]
 [8 7]
 [9 0]]


2

In [117]:
# shape
arr.shape

(5, 2)

In [119]:
# number of elements
arr.size

10

In [121]:
# datatype
arr.dtype

dtype('int32')

10. create a 2D array and access:
- the first row
- the second column
- the last element

In [128]:
array_2d = np.array([[1,2],[3,4]])
print(array_2d)

[[1 2]
 [3 4]]


In [156]:
# first row
array_2d[0]

array([1, 2])

In [136]:
# second column
array_2d[1]

array([3, 4])

In [154]:
# last element
array_2d[(1,1)]

4